name: Validate
on: pull_request
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: |
          cd generator
          npm install
      - name: Generate
        run: |
          cd generator
          node .
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: output
          path: generator/output